### ISSUE TITLE
I don't understand what it does

### ISSUE THREAD

**Issue by orefalo** [EasyGraphQL/easygraphql-load-tester#18]
Hi, sorry.. but I don't understand why this project does.

I spent 20 minutes reading the doc and even part of the core. I don't understand the benefits.
Maybe a one liner in the intro could help.

How is this different than using the k6 API to make http (graphQL) queries?
Also I don't understand the benefits of loadtesting a schema without resolvers?

**Comment by estrada9166** [comment]
Thanks for asking!! The benefits of using this project is that you dont have to write the queries that are going to be used to make http request to your server.

> Also I don't understand the benefits of loadtesting a schema without resolvers?

Actually you’re doing loadtesting to your server, so it’s going to include your resolvers... the schema is used to create all the queries, so you don’t have to write them, but also, you can add custom queries and select which ones should be created (by default it create all the queries that you have on your schema)

[Here](https://twitter.com/estrada9166/status/1076228096972472321?s=21) is a short video using easygraphql-load-tester and artillery that might be useful to get a better idea

**Comment by orefalo** [comment]
got it. great idea and time saver indeed.

thank you.
  Back in the time, I remember playing with a testing framework called agitator. it was for unit testing and the framework would tested all possible combinaisons against a given class.

Which brings me to my next question: 
1. How can I easily get the list of generated queries (I think that's the .json file)
2. How would you implement constraints on parameters. For instance ranges on an attribute.

Thank you

**Comment by estrada9166** [comment]
You can have a list of the generated queries, as you said is the `.json` file, it is going to be generated when you set the option `queryFile: true`, [here](https://github.com/EasyGraphQL/easygraphql-load-tester#query-file) you can find the documentation.

Sorry, can you explain me a little bit more `#2` please!

**Comment by estrada9166** [comment]
@orefalo Can we close this issue?

Thanks!

**Comment by orefalo** [comment]
sure
