### ISSUE TITLE
Please provide a GraphQL mutation example

### ISSUE THREAD

**Issue by Ivan-Marquez** [EasyGraphQL/easygraphql-load-tester#19]
Hi @estrada9166!

I was able to configure the queries and so far is working great! Now I would like to use it with a mutation. I'm passing the mutation name in the `selectedQueries` array field, but it just ignores it. Could you please provide an example of how to setup a mutation? Thanks!

**Comment by estrada9166** [comment]
That's awesome!! for the moment, it doesn't work with mutations because it'll create new data on your db... but for sure, it's something that I'll start working on soon!

The idea can be passing the mutations with a flag on the options, that way, it'll be safe to create the mutations and prevent creating the virtual user data...

also, if you want to create a PR with this, it'll be awesome! I can help if you want!

**Comment by estrada9166** [comment]
@Ivan-Marquez There's a new version that supports mutations, what you have to do is on the options that you pass, you set a new property that is going to be `withMutations: true`

Example:
```
const testCases = easyGraphQLLoadTester.artillery({
  withMutations: true
})
```
Also, don't forget to set the values of input on the args... Check [this](https://github.com/EasyGraphQL/easygraphql-load-tester/blob/master/examples/artillery/index.js#L19) example

Let me know if it works for you and we can close this issue!

Thanks!

**Comment by Ivan-Marquez** [comment]
@estrada9166 I tested it and it's working with mutations. Thank you for all your help!

**Comment by estrada9166** [comment]
@Ivan-Marquez That's awesome!!

I'll close this issue!

**Comment by raheelriax** [comment]
I am facing this issue while using `easygraphql-load-tester` with k6. I've a large schema n I only want to run One specific query and one specific mutation, but only queries are seems to be working

I am passing arguments for both in `LoadTesting` constructor

```
const loadTester = new LoadTesting(userSchema, {
  processSegments:{},
  createProcessSegment: {
    data: <value>,
  },
});
loadTester.k6('k6.js', {
  vus: 10,
  iterations: 10,
  duration: '10s',
  queryFile: true,
  withMutation: true,
  selectedQueries: ['createProcessSegment,processSegments'],
  out: ['json=results.json'],
});

```
