### ISSUE TITLE
Must check the data type (Check for the schema data type) instead pushing it as String, there are instances of selectedArg[key] is either Number or Boolean

### ISSUE THREAD

**Issue by macuvex** [EasyGraphQL/easygraphql-load-tester#39]
https://github.com/EasyGraphQL/easygraphql-load-tester/blob/32da51adacb748397f7c31e8bf8ed3c96d2c6234/utils/util.js#L54

**Comment by dcgomesbr** [comment]
I'm having this issue here, it also fails for Float types. The double quotes cannot be present or else you get:
`"message": "Expected type Boolean, found \"false\"."`

**Comment by estrada9166** [comment]
@macuvex @dcgomesbr Sorry the delay. This may be fixed in the [`v1.0.0-beta.2`](https://www.npmjs.com/package/easygraphql-load-tester/v/1.0.0-beta.2)
If you can give it a try it'll be awesome!

**Comment by estrada9166** [comment]
This is fixed on [`v2.0.1`](https://www.npmjs.com/package/easygraphql-load-tester/v/2.0.1)
