### ISSUE TITLE
Cannot provide null values for optional arguments

### ISSUE THREAD

**Issue by landau** [EasyGraphQL/easygraphql-load-tester#47]
Given a query with nullable args, such as

```graphql
{
  # both args optional
  stuff(a: String b:String): Stuff
}
```

I should able to provide either `a`, `b`, or neither as arguments, but instead receive an error stating, for example, `All query arguments must be defined - missing a`.

It doesn't seem to make sense to assert these arguments unless GraphQL schema requires them.

Thanks!

**Comment by estrada9166** [comment]
Thanks! it should be fixed in `v0.3.8`
