### ISSUE TITLE
Support multiple args for a given query

### ISSUE THREAD

**Issue by landau** [EasyGraphQL/easygraphql-load-tester#48]
Some GraphQL queries might accept optional arguments in which one would want to test different arguments. 

Imagine the following schema

```
{
  # both args optional
  stuff(a: String b:String): Stuff
}
```

It would be great to provide the following as arguments for a single query

```js
{
  stuff: [
     // since both `a` and `b` are optional
    {a: null, b: null}, 
    // Load test with `a` as the arg
    { a: 'foo' },
    // Load test with `b` as the arg
    { b: 'bar' }
  ]
}
```

Thank you.

**Comment by estrada9166** [comment]
@landau That's awesome, thanks!

It is supported on [`v1.0.0-beta.2`](https://www.npmjs.com/package/easygraphql-load-tester/v/1.0.0-beta.2)
If you can give it a try it'll be awesome!

**Comment by estrada9166** [comment]
This is supported on [`v2.0.1`](https://www.npmjs.com/package/easygraphql-load-tester/v/2.0.1)
