### ISSUE TITLE
Old version 2.0.1 on npm

### ISSUE THREAD

**Issue by mircicd** [EasyGraphQL/easygraphql-load-tester#68]
Hi

Not sure if this is the right channel but I just wanted to let you know that the latest package of 2.0.2 on npm seems to be still containing 2.0.1 code.
To verify, download the tarball from npm:
https://registry.npmjs.org/easygraphql-load-tester/-/easygraphql-load-tester-2.0.1.tgz
Open up `package/lib/index.js` and navigate to lines `74` and `75`. You'll see that the env still contains the old 2.0.1 definitions `VUS` and `DURATION` which were changed in one of the 2.0.2 commits:
https://github.com/EasyGraphQL/easygraphql-load-tester/commit/79919b1f2ee58405ab7a81a57103e52117c58333

I ran into an issue with k6 loadtesting because of this (vus wouldn't get picked up from my initializer).

Cheers

**Comment by estrada9166** [comment]
I'm not sure why it happened but now there's a new version `v2.0.3` which is working as expected!

Thanks.
