### ISSUE TITLE
query test is testing query with all possible combinations not JUST the return value I requested.

### ISSUE THREAD

**Issue by astavria4** [EasyGraphQL/easygraphql-load-tester#85]
Hi, 
I am using spacex as my target: https://api.spacex.land/graphql/

I am testing with the query:
const queries = [
    ` query SEARCH_MISSION($id: ID!) {
        mission(id: $id) {
          name
        }
      }
    `,
  ]

in my schema, this query exists: mission(id: ID!): Mission

Im passing in multiple args:
  const args = {
     mission: [
       {
         id: '9D1B7E0'
       },
       {
       id: 'F4F83DE'
       }

     ]
   }  

and I am setting the artillery options as:
const options = {
  selectedQueries: ['mission'],
  queryFile:true
  }

The testCases are running. But, when I look at the queryFile, I see that the mission query is being tested with all of the different combinations for return values (check below). If you go to the spacex playground, you can see that under the mission query, description is the first return value, then id, then manufacturers and then name. However, in my custom query I asked for only name to be returned. 

    {
        "name": "mission with arguments: { id: $id }",
        "query": "\n    query MISSION($id: ID!) {\n        mission(id: $id) {\n      description id manufacturers name\n    }\n      }\n    ",
        "operation": "Query",
        "variables": {
            "id": "9D1B7E0"
        }
    },
    {
        "name": "mission with arguments: { id: $id }",
        "query": "\n    query MISSION($id: ID!) {\n        mission(id: $id) {\n      description id manufacturers name\n    }\n      }\n    ",
        "operation": "Query",
        "variables": {
            "id": "F4F83DE"
        }
    },
    {
        "name": "mission with arguments: { id: $id }",
        "query": "\n    query MISSION($id: ID!) {\n        mission(id: $id) {\n      description id manufacturers name twitter\n    }\n      }\n    ",
        "operation": "Query",
        "variables": {
            "id": "9D1B7E0"
        }
    },
    {
        "name": "mission with arguments: { id: $id }",
        "query": "\n    query MISSION($id: ID!) {\n        mission(id: $id) {\n      description id manufacturers name twitter\n    }\n      }\n    ",
        "operation": "Query",
        "variables": {
            "id": "F4F83DE"
        }
    },
    {
        "name": "mission with arguments: { id: $id }",
        "query": "\n    query MISSION($id: ID!) {\n        mission(id: $id) {\n      description id manufacturers name twitter website\n    }\n      }\n    ",
        "operation": "Query",
        "variables": {
            "id": "9D1B7E0"
        }
    },
    {
        "name": "mission with arguments: { id: $id }",
        "query": "\n    query MISSION($id: ID!) {\n        mission(id: $id) {\n      description id manufacturers name twitter website\n    }\n      }\n    ",
        "operation": "Query",
        "variables": {
            "id": "F4F83DE"
        }
    },

**Comment by estrada9166** [comment]
In this case, I think you want to use something like

```js
const options = {
  customQueries: queries,
  onlyCustomQueries: true,
  queryFile: true,
}

```

**Comment by astavria4** [comment]
Hi @estrada9166, thanks for getting back to me. You suggestion works!
